-- This script creates the join table to store the many-to-many relationship
-- between users and their contacts.

CREATE TABLE IF NOT EXISTS public.contact_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    contact_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- A user can only have a specific contact once.
    UNIQUE(user_id, contact_user_id)
);

-- Enable RLS
ALTER TABLE public.contact_relationships ENABLE ROW LEVEL SECURITY;

-- Policies for contact_relationships
-- Users can view their own contact list
CREATE POLICY "Users can view their own contact relationships"
ON public.contact_relationships
FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own contacts
CREATE POLICY "Users can add to their own contact list"
ON public.contact_relationships
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can delete their own contacts
CREATE POLICY "Users can delete their own contacts"
ON public.contact_relationships
FOR DELETE
USING (auth.uid() = user_id);
