CREATE TABLE public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id uuid NOT NULL,
    receiver_id uuid NOT NULL,
    content text NOT NULL,
    image_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Optional: Add indexes for performance
CREATE INDEX messages_sender_id_idx ON public.messages (sender_id);
CREATE INDEX messages_receiver_id_idx ON public.messages (receiver_id);
